### PyTorch函数介绍
本节参考《Python深度学习——基于PyTorch》代码和PyTorch官方文档 https://pytorch.org/tutorials/

PyTorch官方网页中Docs栏有函数的介绍，Tutorails栏有简单教程，是很好的参考和学习资料

1. PyTorch提供了一些基本的tensor操作，不仅能对tensor进行运算，也可以查看tensor对象的各种属性，本节主要介绍一些常用的运算操作

In [1]:
import torch
print(torch.__version__)

1.7.0


In [2]:
torch.manual_seed(2022) # 设置随机化种子
# 创建随机矩阵
r = (torch.rand(2, 2) - 0.5) * 2 # 生成值在 -1 和 1 之间的随机矩阵
print(r)

tensor([[-0.2084,  0.8439],
        [ 0.5176, -0.2377]])


In [3]:
# 取绝对值
print(torch.abs(r))

tensor([[0.2084, 0.8439],
        [0.5176, 0.2377]])


In [4]:
# 四舍五入
print(torch.round(r))
# 向上取整
print(torch.ceil(r))
# 向下取整
print(torch.floor(r))

tensor([[-0., 1.],
        [1., -0.]])
tensor([[-0., 1.],
        [1., -0.]])
tensor([[-1.,  0.],
        [ 0., -1.]])


In [5]:
# 三角函数相关也是支持的
# arcsin
print(torch.asin(r))
# cos
print(torch.cos(r))
# 
import math
a = torch.tensor([0, math.pi / 4, 3 * math.pi / 4])
print(torch.tan(a))

tensor([[-0.2099,  1.0045],
        [ 0.5440, -0.2400]])
tensor([[0.9784, 0.6646],
        [0.8690, 0.9719]])
tensor([ 0.,  1., -1.])


In [6]:
# 计算方阵行列式
print(torch.det(r))
# 方阵SVD分解
print(torch.svd(r))

tensor(-0.3873)
torch.return_types.svd(
U=tensor([[ 0.8868, -0.4621],
        [-0.4621, -0.8868]]),
S=tensor([0.9573, 0.4046]),
V=tensor([[-0.4429, -0.8966],
        [ 0.8966, -0.4429]]))


In [7]:
# 计算矩阵的统计量，例如均值、标准差等
# 计算标准差和均值
print(torch.std(r))
print(torch.mean(r))

tensor(0.5387)
tensor(0.2288)


In [8]:
# 计算最大值、最小值
print(torch.max(r))
# 也可以计算argmax等
print(torch.argmax(r))
# 上面的操作都可以指定维度进行操作

tensor(0.8439)
tensor(1)


In [9]:
# 限制值的范围
print(torch.clamp(r, 0, 1))

tensor([[0.0000, 0.8439],
        [0.5176, 0.0000]])


In [10]:
a = torch.rand(2, 3)
print(a.shape)
# 矩阵的转置
b = a.T
print(b.shape)
# 改变张量形状
c = a.view(-1, 1)
print(c.shape)

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([6, 1])


In [11]:
a = torch.rand(2, 3, 4)
print(a.shape)
# 改变张量形状
b = a.reshape(-1, 4)
print(b.shape)
# 高维张量的转置（改变维度的顺序）
b = a.transpose(0, 1)
print(b.shape)
# 改变高维张量维度的顺序
b = a.permute(2, 0, 1)
print(b.shape)
# 插入新的维度
b = a.unsqueeze(1)
print(b.shape)
# 去掉第二维
b = a.squeeze(1)
print(b.shape)
# 插入新维度
b = a.unsqueeze(1).unsqueeze(3)
print(b.shape)
# 去掉所有维数为1的维度
b = b.squeeze()
print(b.shape)

torch.Size([2, 3, 4])
torch.Size([6, 4])
torch.Size([3, 2, 4])
torch.Size([4, 2, 3])
torch.Size([2, 1, 3, 4])
torch.Size([2, 3, 4])
torch.Size([2, 1, 3, 1, 4])
torch.Size([2, 3, 4])


In [12]:
a = torch.ones(2, 2) * 0.5
b = torch.ones(2, 2) * 2.0
print(a * b)    # 对应元素相乘
print((torch.matmul(a, b))) # 矩阵乘法

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [13]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 6)
# 张量中的矩阵分批次相乘
c = torch.bmm(a, b)
print(c.shape)

torch.Size([3, 4, 6])


In [14]:
a = torch.rand(2, 2)
print(a)
# 生成和 a 形状相同的全零矩阵
print(torch.zeros_like(a))
# 生成和 a 形状相同的全一矩阵
print(torch.ones_like(a))
# 生成和 a 形状相同的随机矩阵
print(torch.rand_like(a))

tensor([[0.8850, 0.0986],
        [0.0030, 0.8304]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.2150, 0.5212],
        [0.7944, 0.4251]])


In [15]:
# 类型转换
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = a.double()
print(b)

c = a.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [16]:
# 张量的复制
a = torch.ones(2, 2)
b = a
# a 和 b 指向同一块内存
a[0][1] = 561  
print(b)       

tensor([[  1., 561.],
        [  1.,   1.]])


In [17]:
a = torch.ones(2, 2)
b = a.clone()
# a 和 b 内容相同，但不是同一块内存
print(torch.eq(a, b))   # 判断张量对应位置的值是否相等
a[0][1] = 561
print(b)   

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [18]:
a = torch.rand(2, 2, requires_grad=True)
print(a)
# clone会保存计算图的信息
b = a.clone()
print(b)
# detach可以将张量从计算图中剥离
c = a.detach().clone()
print(c)

print(a)

tensor([[0.7436, 0.0212],
        [0.0590, 0.9506]], requires_grad=True)
tensor([[0.7436, 0.0212],
        [0.0590, 0.9506]], grad_fn=<CloneBackward>)
tensor([[0.7436, 0.0212],
        [0.0590, 0.9506]])
tensor([[0.7436, 0.0212],
        [0.0590, 0.9506]], requires_grad=True)


2. PyTorch张量求梯度

In [19]:
a = torch.tensor(2., requires_grad=True)
print(a)
b = a + 1.
print(b)
c = 2 * a
print(c)
d = b * c 
print(d)
# PyTorch的计算图会记录计算的方式和对应的张量
# 叶子节点grad_fn为None
print(a.is_leaf)
print(b.is_leaf)

tensor(2., requires_grad=True)
tensor(3., grad_fn=<AddBackward0>)
tensor(4., grad_fn=<MulBackward0>)
tensor(12., grad_fn=<MulBackward0>)
True
False


In [20]:
# 使用函数直接计算两个变量之间的梯度
print(torch.autograd.grad(d, b))
# 使用上面的函数计算梯度后，计算图会释放，因此再次运行该命令会报错
# 但是张量不会保存梯度信息
print(b.grad)

(tensor(4.),)
None


C:\Miniconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """


In [21]:
# 求梯度的第二种方式，会保存叶子节点的梯度信息
a = torch.tensor(2., requires_grad=True)
b = a + 1.
c = 2 * a
d = b * c 

d.backward()
print(a.grad)
print(b.grad)

tensor(10.)
None


C:\Miniconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  if __name__ == '__main__':


In [22]:
d1 = 3 * a
d1.backward()
# 梯度会累加
print(a.grad)

tensor(13.)


In [23]:
d2 = a * (a + 1)
a.grad.data.zero_()
d2.backward()
print(a.grad)

tensor(5.)
